### PR TITLE
fix: update for V9

### PR DESCRIPTION
**Pull request by arcanistzed**

### CODE REVIEW

**Comment by arcanistzed** [comment]
Could I enter this for [hacktoberfest](https://hacktoberfest.digitalocean.com/)? You just need to add the `hacktoberfest-accepted` label :slightly_smiling_face:

**Comment by Malekal4699** [comment]
Hi, I've added branch 0.9.x, can you apply your changes to that one? thanks.

**Comment by arcanistzed** [comment]
Sure, will do. Just a note that there is a distinction between "v9" and "0.9.x" (which is the wrong version number). Consequently, you should simply put `9` in the manifest for the compatible and minimum core version 🙂

**Comment by arcanistzed** [comment]
Ok, I fixed the version numbers and changed the base of the PR to the 0.9.x branch

**Comment by arcanistzed** [comment]
Will a new release be made?

**Pull request merged**
